name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.27.204.8 << 'EOF' 
        cd /home/ec2-user/git/software-engineering-lab2
        git pull origin main
        EOF

    - name: Rebuild docker image
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.27.204.8 << 'EOF' 
        cd /home/ec2-user/git/software-engineering-lab2
        docker build -t myapp .
        EOF

    - name: Restart Docker Container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.27.204.8 << 'EOF' 
        docker stop my_container
        docker rm my_container
        docker run -d -p 80:80 --name my_container myapp
        EOF
