name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Restart Docker Container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.27.204.8 << 'EOF'
        "docker stop my_container || true"
        "docker rm my_container || true"
        "docker run -d -p 80:80 --name my_container myapp"
        EOF
