name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v.0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.27.204.8
      scp -o StrictHostKeyChecking=no index.html ec2-user@3.27.204.8:/home/ec2-user/git/software-engineering-lab2
    - name: Restart Docker Container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.27.204.8
        "docker stop my_container || true"
        ssh -o StrictHostKeyChecking=no ec2-user@3.27.204.8
      "docker run -d -p 80:80 --name my_container -v /home/ec2-user/git/software-engineering-lab2:/usr/share/nginx/html myapp"
